### PR TITLE
Exclude `$projectRoot/package.json` from assets

### PR DESCRIPTION
**Pull request by robertying**
**Summary**

From https://github.com/facebook/metro/commit/dcb41e39f0df6ae1e0b3dfeff9ef5a69128830d5#diff-235a3e5d21175615e1cc254dd8b17eb2, files with `json` extension will be considered as assets and returned as `outputAssets` for `@react-native-community/cli`.

This means `cli` will copy files with `json` extension to resource dir, in Android's case, `android/app/build/res`.

Here comes a problem. If `package.json` at the project root gets copied, it won't be renamed as other `package.json` in `node_modules` (e.g. `raw/node_modules_reactnativecodepush_package.json`). Instead, it will reside in `res` as `package.json`, which causes the error:

https://github.com/facebook/react-native/issues/25325

```
android/app/src/main/res/raw/package.json: Error: package is not a valid resource name (reserved Java keyword)
```

This regression (I believe ;)) was introduced to React Native 0.60.0-rc with metro bumping from 0.51 to 0.54.

**Possible impact**

1. Typical usage concerning `package.json` at the root will be something like `import packageJson from "./package.json"` in JS files to get some project configurations and those content will be bundled into `index.android.bundle` no matter what. So removing `$projectRoot/package.json` won't have too much impact.

2. This new (or bad?) behavior has only been in React Native 0.60-rc so it won't affect current projects running 0.59. It should be fixed before the final release of 0.60, I assume.

**Test plan**

1. `react-native init resoucesRepro --version react-native@next` (so it uses 0.60.0-rc)
1. Add `import packageJson from './package.json'` to `App.js`.
1. `cd android && ./gradlew assembleRelease`
1. Get the error.
1. Modify `node_modules/metro/src/DeltaBundler/Serializers/getAssets.js` to match this commit.
1. `cd android && ./gradlew assembleRelease`
1. It now works!

### CODE REVIEW

**Comment by bneigher** [comment]
please merge!

**Comment by IgorBelyayev** [comment]
Temporary fix while we wait for this to be merged.

Add this script to the root project directory and run it `postinstall`:

```
// fix_metro_android_release_bug.js
// Temporary fix for this issue: https://github.com/facebook/metro/pull/420
const fs = require('fs');

const fileLocation = './node_modules/metro/src/DeltaBundler/Serializers/getAssets.js';
const targetText = 'getJsOutput(module).type === \'js/module/asset\'';
const replacementText = 'getJsOutput(module).type === \'js/module/asset\' && path.relative(options.projectRoot, module.path) !== \'package.json\'';

const fileContent = fs.readFileSync(fileLocation, 'utf8');
if (fileContent.includes(targetText) && !fileContent.includes(replacementText)) {
  const patchedFileContent = fileContent.replace(targetText, replacementText);
  fs.writeFileSync(fileLocation, patchedFileContent, 'utf8');
}
```

Then, inside your inside your `package.json`:
```
  "scripts": {
    "postinstall": "babel-node ./fix_metro_android_release_bug.js",
    ...
  }
```

The script applies the changes from this PR.

**Comment by bneigher** [comment]
@IgorBelyayev love it ahaha

**Comment by CgarciaTC** [comment]
> Solución temporal mientras esperamos que esto se fusione.
> 
> Agregue este script al directorio raíz del proyecto y ejecútelo `postinstall`:
> 
> ```
> // fix_metro_android_release_bug.js
> // Temporary fix for this issue: https://github.com/facebook/metro/pull/420
> const fs = require('fs');
> 
> const fileLocation = './node_modules/metro/src/DeltaBundler/Serializers/getAssets.js';
> const targetText = 'getJsOutput(module).type === \'js/module/asset\'';
> const replacementText = 'getJsOutput(module).type === \'js/module/asset\' && path.relative(options.projectRoot, module.path) !== \'package.json\'';
> 
> const fileContent = fs.readFileSync(fileLocation, 'utf8');
> if (fileContent.includes(targetText) && !fileContent.includes(replacementText)) {
>   const patchedFileContent = fileContent.replace(targetText, replacementText);
>   fs.writeFileSync(fileLocation, patchedFileContent, 'utf8');
> }
> ```
> 
> Entonces, dentro de tu interior tu `package.json`:
> 
> ```
>   "scripts": {
>     "postinstall": "babel-node ./fix_metro_android_release_bug.js",
>     ...
>   }
> ```
> 
> El script aplica los cambios de este PR.

disculpa, cual seria la raiz de mi proyecto???

**Comment by robertying** [comment]
@cpojer this commit does not seem to be included in the latest release (0.56.0)'s npm package. Can you please take a look into this? Thanks!

**Comment by cdunkel** [comment]
I'm also on 0.56.0 and still seeing this issue. Any updates?

**Comment by cdunkel** [comment]
@robertying, I had to update to RN 0.61.x in order to pick up this change, if that helps.

**Comment by robertying** [comment]
@cdunkel thanks! I think 0.61 now includes this patch.

**Pull request closed without merging**
