### PR TITLE
Update hash function for node 17 compatibility

### LINKED ISSUE #722: got ERR_OSSL_EVP_UNSUPPORTED when using node 17 and react 17 on expo
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
the error is coming from metro.
one way to get it is to run "expo start".
it returns a qrcode and then shows this error : ERR_OSSL_EVP_UNSUPPORTED

im sorry i dont know how to acces metro config/parameters.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
```
# npm install -g expo-cli
# expo init my-app
# cd my-app
# expo start
Logs for your project will appear below.
Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at stableHash (/root/docker/gextrareact/node_modules/metro-cache/src/stableHash.js:19:8)
    at Object.getCacheKey (/root/docker/gextrareact/node_modules/metro-transform-worker/src/index.js:647:7)
    at getTransformCacheKey (/root/docker/gextrareact/node_modules/metro/src/DeltaBundler/getTransformCacheKey.js:32:19)
    at new Transformer (/root/docker/gextrareact/node_modules/metro/src/DeltaBundler/Transformer.js:180:28)
    at /root/docker/gextrareact/node_modules/metro/src/Bundler.js:58:29 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**What is the expected behavior?**
working

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

metro : 0.64.0

System:
OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
Shell: 5.0.17 - /bin/bash
Binaries:
Node: 17.0.1 - /usr/local/bin/node
Yarn: 1.22.15 - /usr/local/bin/yarn
npm: 8.1.1 - /usr/local/bin/npm
npmPackages:
expo: ^43.0.0 => 43.0.0
react: 17.0.1 => 17.0.1
react-dom: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2
npmGlobalPackages:
expo-cli: 4.12.10
Expo Workflow: managed

### PR DESCRIPTION
**Pull request by tobua**
When running a RN project currently with node 17 it will fail because a deprecated hash function is used with the [node crypto library](https://nodejs.org/en/blog/release/v17.0.0/#openssl-3-0). The error is `ERR_OSSL_EVP_UNSUPPORTED` and will always appear unless a flag is explicitly set. Only the `metro-cache` package is affected. The stable version node 17 has been around for 3 months and will become active LTS in April of this year.

**Summary**

Switching from a 128 bit `md4` hash to another 128 bit `md5` hash that's safe is enough to fix the issue. However, note that I'm neither a hash function nor a metro cache expert.

**Test plan**

Tested with stable node 17, with LTS node 16 and also works fine with lowest supported node 12 version.
An already built project can be upgraded without the need to clear the cache.

Fixes #722

Couldn't find any related issues in the main RN repository.

### CODE REVIEW

**Comment by rh389** [comment]
Thanks for the PR - and yep as confirmed below, clearly an issue with our (any) use of md4.

```sh
$ node -e "require('crypto').createHash('md4');"
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at [eval]:1:19
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:305:38)
    at node:internal/process/execution:75:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:74:60)
    at node:internal/main/eval_string:27:3 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0
```

**Comment by rh389** [comment]
We switched from md5->md4 in https://github.com/facebook/metro/commit/a4c417a1c5ecadf528692b0f11b1e52c75051ef3 for a marginal performance gain.

Here's a very quick-and-dirty benchmark on node 16 on my MBP, which looks like a tiny perf hit when _purely_ hashing:

```
➜  ~ REPEATS=2000000 node bench1.js
md4 took 6.284265818953514s with 2000000 repeats
md5 took 6.490958640933036s with 2000000 repeats
sha1 took 6.5310690860748295s with 2000000 repeats
```

<details>
<summary>bench1.js</summary>

```js
const crypto = require('crypto');
const { performance } = require('perf_hooks');

const content = JSON.stringify(performance); // length: 356

for (const algo of ['md4', 'md5', 'sha1']) {
  const start = performance.now();
  for (let i = 0; i < process.env.REPEATS; i++) {
	crypto.createHash(algo).update(content).digest();
  }
  console.log(`${algo} took ${(performance.now() - start) / 1000}s with ${process.env.REPEATS} repeats`);
}
```
</details>

But introducing `JSON.stringify` into the loop (as we do in `stableHash`) and they're inseparable.

```sh
➜  ~ REPEATS=2000000 node bench2.js
md4 took 14.407320219039917s with 2000000 repeats
md5 took 14.338770728945732s with 2000000 repeats
sha1 took 14.607237200021745s with 2000000 repeats
```

<details>
<summary>bench2.js</summary>

```js
const crypto = require('crypto');
const { performance } = require('perf_hooks');

for (const algo of ['md4', 'md5', 'sha1']) {
  const start = performance.now();
  for (let i = 0; i < process.env.REPEATS; i++) {
	crypto.createHash(algo).update(JSON.stringify(performance)).digest();
  }
  console.log(`${algo} took ${(performance.now() - start) / 1000}s with ${process.env.REPEATS} repeats`);
}
```
</details>

**Comment by tobua** [comment]
@rh389 webpack switched from md4 to their [own xxhash64 implementation](https://github.com/webpack/webpack/blob/c60fc2fae533461bc654742b6024bea3071d8870/lib/util/hash/xxhash64.js) because of the node 17 deprecation. I would assume that would be quite a bit faster (relies on WebAssembly) than md4 but the effort seems quite significant.

**Comment by rh389** [comment]
`xxhash-wasm` looks interesting thanks, noted.

For now, apparently `stableHash` is no longer used for anything performance sensitive anyway, so this PR has a green light and will be merged in an hour or two. Thanks again!

**Comment by tobua** [comment]
@rh389 Awesome, appreciate the quick response!

**Pull request closed without merging**
