### PR TITLE
Fix failure to resolve module if it looks like an asset (e.g. core-js $.html.js)

### PR DESCRIPTION
**Pull request by haggholm**
**Summary**

Fix https://github.com/facebook/react-native/issues/20721

Currently, the way the bundler checks if something is an asset or a source module is purely based on filename. This breaks in edge cases as found in `core-js` where there’s a file called `$.html.js` which is imported as `'./$.html'`. Based purely on filename, it looks like an asset; in fact, it’s a JS file, but Metro fails to find it.

**Test plan**

I’ll be honest here, I do not really understand how the Metro tests are written. I’ve verified it ‘manually’ by checking that Metro makes it past the `core-js` error, but I would be grateful for help with a test.

### CODE REVIEW

**Comment by designtesbrot** [comment]
bump

**Comment by cpojer** [comment]
cc @mjesun

**Comment by cpojer** [comment]
Could you rebase this?

**Comment by cpojer** [comment]
Closing due to inactivity.

**Pull request closed without merging**
