### PR TITLE
Extract `node-haste` to new `metro-dependency-graph` module

### PR DESCRIPTION
**Pull request by skevy**
**Summary**

I've been meaning to do this for a while, and finally got around to finishing this PR.

I'd like to use the Metro dependency graph as a separate package for some work at Airbnb. This PR extracts all the existing dependency graph code (previously in `node-haste` directory) to a new `metro-dependency-graph` package.

No functionality should have changed, and besides changing imports, most of this diff should just be shifting files around.

It's worth noting that there may be follow ups needed to make this module truly useful outside of Metro, but this is step 1.

**Test plan**

Run tests.

cc @mjesun @rafeca

### CODE REVIEW

**Comment by cpojer** [comment]
@mjesun I know you had some plans around this code, could you comment here and then make a decision on this PR?

**Comment by skevy** [comment]
@cpojer @mjesun any updates?

**Comment by cpojer** [comment]
I'm happy to finally get rid of the "node-haste" folder. If you rebase, I can land it.

**Comment by cpojer** [comment]
Dang, sorry @skevy I didn't get a notification when you pushed. Do you mind doing one more rebase and then commenting here so I can actually merge it?

**Comment by cpojer** [comment]
@skevy are you still interested in landing this?

**Comment by cpojer** [comment]
I guess not :(

**Comment by skevy** [comment]
@cpojer ha sorry I missed your messages. I am actually interested in finishing this, just not sure when I’ll have time to do it. Closing for now is totally fine — I’ll get it done one of these days! Thanks for keeping me honest.

**Pull request closed without merging**
