### PR TITLE
[metro-visualizer] Add README and development script

### PR DESCRIPTION
**Pull request by simonpfish**
**Summary**

A README was added to the `metro-visualizer` package with an overview of the tool and setup instructions. 

Additionally, a simple script that spawns a metro server for testing the visualizer was added to the package. 

Note: I just completed the CLA for the first time. 

**Test plan**

Read through the README. Run the development script from the `metro-visualizer` root folder and point the browser at http://localhost:8080/visualizer to make sure that the server is spawned correctly.

### CODE REVIEW

**Comment by rafeca** [comment]
Thanks @simonpfish and sorry for the delay reviewing! I'm gonna import this into phabricator 😃

**Comment by rtmalone** [comment]
Hi, I realize this is still open. but I'm trying to get the visualizer to work and this is the only place I have found with any instructions. I'm stuck at a place where I think I need to see whether a specific package is being included in the bundle. When I following the instructions here and visit `localhost:8081/visualizer` I receive
```
Unable to resolve module `react` from `/Users/my/path/to/project/node_modules/metro- visualizer/src/app/index.js`: Module `react` does not exist in the Haste module map or in these 
directories: /Users/my/path/to/project/node_modules
```
That's untrue however. React is definitely in my node_modules as it is a dep of every react-native related package.

**Comment by simonpfish** [comment]
Hey! You might have to cd into the metro-visualizer package directory and run `npm install` or `yarn` there. Let me know if this fixes anything, I can look more into it if it doesn't.

**Comment by roytan883** [comment]
@simonpfish follow the README, can't make it work. check #373 
maybe you should write more clear about how to start it, and with which version of RN.
I start it with `yarn run metro serve`, but can't build bundle, always says "Module `AccessibilityInfo` does not exist in the Haste module map". 
which version of RN can work with `metro-visualizer` ?

**Pull request closed without merging**
