### PR TITLE
Add support for .mjs and .cjs file extensions

### LINKED ISSUE #59: Is the `.mjs` file extension resolved by metro bundler?
Hi all, quick question as library maintainer, is the `.mjs` file extension supported by metro? In order words, will a package json with a `module` field like this work like with webpack (or is `module` ignored completely, which would be fine as well):

`"module": "lib/mobx.mjs"`

### LINKED ISSUE #535: Add .cjs and .mjs files support
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If you have `require('./index.cjs')` you will have issue:

```
Error: While trying to resolve module `lib` from file `project/index.js`, the package `project/node_modules/lib/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`project/node_modules/lib/index.cjs`. Indeed, none of these files exist:

      * project/node_modules/lib/index.cjs(.native|.web.js|.native.js|.js|.web.json|.native.json|.json|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx)
      * project/node_modules/lib/index.cjs/index(.native|.web.js|.native.js|.js|.web.json|.native.json|.json|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx)
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

1. Create empty project
2. Add `lib.cjs`
3. Create `index.js` with `require('./lib.cjs')`

**What is the expected behavior?**

Load `.cjs` files as any `.js` files.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**

* No Metro config
* Metro 0.59.0
* Node 13.11.0
* Yarn 1.22.4

**Extra details**

I opened this issue because users of my dual CJS/ESM project have a problem with using my lib to React Native
https://github.com/ai/nanoevents/issues/44#issuecomment-601722303

You had [`.mjs` issue before](https://github.com/facebook/metro/issues/59), but it was closed because in 2017 it was not clear about `.mjs` standard. Now `.mjs` and `.cjs` is an [official Node.js API](https://nodejs.org/api/modules.html#modules_addenda_the_mjs_extension).

### PR DESCRIPTION
**Pull request by LinusU**
**Summary**

Node.js have added support for the `.mjs` and `.cjs` extensions which many packages have started using. This pull request adds these two file extensions so that packages using them can still be loaded with Metro.

This was specifically prompted by `@apollo/client`, a popular package that can be used from React Native, changing the file extension to `.cjs` which broke compatibility with Metro.

> - [Relevant if you use Apollo Client with React Native] Since Apollo Client v3.5.0, CommonJS bundles provided by `@apollo/client` use a `.cjs` file extension rather than `.cjs.js`, so Node.js won't interpret them as ECMAScript modules. While this change should be an implementation detail, it may cause problems for the [Metro bundler](https://facebook.github.io/metro/) used by React Native, whose [`resolver.sourceExts`](https://facebook.github.io/metro/docs/configuration#sourceexts) configuration does not include the `cjs` extension by default.
> 
>   As a workaround until [this issue](https://github.com/facebook/metro/issues/535) is resolved, you can configure Metro to understand the `.cjs` file extension by creating a `metro.config.js` file in the root of your React Native project:
>   ```js
>   const { getDefaultConfig } = require("metro-config");
>   const { resolver: defaultResolver } = getDefaultConfig.getDefaultValues();
>   exports.resolver = {
>     ...defaultResolver,
>     sourceExts: [
>       ...defaultResolver.sourceExts,
>       "cjs",
>     ],
>   };
>   ``` 

Fixes #535
Fixes #59
Fixes #60

**Test plan**

In a temporary directory:

1. `npx react-native@latest init TestSourceExts` 
2. `cd TestSourceExts`
3. `npx react-native run-ios`
    1. Check that project works
    2. Close everything opened
4. `yarn add @apollo/client graphql`
5. Add `import { ApolloProvider } from '@apollo/client'` to top of `app.js`
6. Add the following snippet to the `<App />`
    ```js
    <Section title="Apollo Import Test">
      Should be function: {typeof ApolloProvider}
    </Section>
    ```
7. `npx react-native run-ios`
    1. Observe the error
    2. Close everything opened
8. Manually patch `node_modules/metro-config/src/defaults/defaults.js`
    ```diff
    - exports.sourceExts = ["js", "json", "ts", "tsx"];
    + exports.sourceExts = ["js", "json", "ts", "tsx", "mjs", "cjs"];
    ```
9. `npx react-native run-ios`
    1. Observe everything gloriously working
    2. Celebrate 🎉

### CODE REVIEW

**Comment by rh389** [comment]
Hi @LinusU - the test failure was unrelated - apologies for the delay. We're discussing a slightly different approach here because currently adding to `sourceExts` does two things:

1. Includes additional extensions in the in-memory file map / watcher, so that Metro is aware of their existence
2. Tries the extensions when resolving imports / requires, eg we'll look for `foo.js` when you `require('./foo')`

Only the first is necessary in this case, because `.cjs`/`.mjs` extensions [must be given explicitly](https://nodejs.org/api/modules.html#file-modules) when using `require`/`import` - in other words `require('./foo')` should never resolve to `./foo.cjs`. Obviously we'd like Metro's defaults to stay as close to node's behaviour as reasonably possible, and there's a performance consideration in having unnecessary resolution candidates too.

We're going to tweak the config format here to allow options for each extension (so we can have 1. without 2.) - something like `sourceExts: Array<string | [string, { resolveImplicit: boolean }]>`. Do you mind if I push this change to your PR?

**Comment by mattwr18** [comment]
I'm not sure if this is the best place to ask this question, but in the hopes it might save someone else considerable time debugging, I'll ask.

We recently added `@apollo/client` to our react native project and ran into the `.cjs` issue. We used the referenced workaround that is in the [Apollo CHANGELOG](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-354-2021-11-19) and ran into an issue with another package, [pubnub](https://github.com/pubnub/javascript).

Somehow, it was detecting that we were in a web environment 🤷 
In the end, we removed the line spreading the `...defaultResolver` and just spread the `sourceExts` and added `'cjs'`.

Any idea what in the `defaultResolver` could have caused this? I noticed there were platforms `[ 'ios', 'android', 'windows', 'web' ]`, but removing `windows` and `web` didn't seem to solve the issue. Maybe, the `resolverMainFields: [ 'browser', 'main' ]` would make some undesirable impact?

Anyways, sorry if this isn't the place for this discussion.

**Comment by tido64** [comment]
@robhogan, @motiz88: Any chance we can get this in? We are hitting this internally as well.

cc @asmundg

**Comment by SohelIslamImran** [comment]
If you are using expo, to resolve this issue, create a **metro.config.js** file in the project root. In the file add the file extension `cjs`. [details](https://docs.expo.dev/guides/customizing-metro/#adding-more-file-extensions-to--assetexts)

```js
const { getDefaultConfig } = require("@expo/metro-config");

const defaultConfig = getDefaultConfig(__dirname);

defaultConfig.resolver.assetExts.push("cjs");

module.exports = defaultConfig;
```


image

**Comment by huntie** [comment]
We have now landed out-of-the-box support for `.cjs` and `.mjs` in c1c6d9c via the `watcher.additionalExts` option. Thanks @LinusU for opening this PR, which has been a great reference for others and brought this to our attention internally 🙂

**Comment by LinusU** [comment]
@huntie that's awesome! I'm glad to hear it 🎉

**Pull request closed without merging**
