### PR TITLE
Fix expo issue [#17903](https://github.com/expo/expo/issues/17903)

### PR DESCRIPTION
**Pull request by gavin1995**
## Summary

Fix expo issue [#17903](https://github.com/expo/expo/issues/17903)

### dependencies

{
    "expo": "45.0.5",
    "expo-location": "~14.2.2",
    "expo-navigation-bar": "~1.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-updates": "~0.13.2",
    "react-native": "0.68.2"
}

### issue

The [file](https://github.com/facebook/metro/blob/main/packages/metro/src/Server.js#L1023) in the [_symbolicate](https://github.com/facebook/metro/blob/main/packages/metro/src/Server.js#L1017) method may be a url link.

### CODE REVIEW

**Comment by edi** [comment]
Need it soon :)

**Comment by nicusbonannus** [comment]
Please review this PR, we also need it

**Comment by tybeck** [comment]
Also needed

**Comment by robhogan** [comment]
On closer investigation, Metro already makes an attempt to check for known URLs here but it was buggy - #910.

**Comment by robhogan** [comment]
Thanks again @gavin1995, closing as this is superseded by #910, now released in [0.74.0](https://github.com/facebook/metro/releases/tag/v0.74.0).

**Pull request closed without merging**
