### PR TITLE
update ws package

### PR DESCRIPTION
**Pull request by gwmccull**
**Summary**

The version of the `ws` package used by metro (`v1.1.5`) has been flagged as having a security vulnerability.

I updated `ws` to the latest version and all tests are passing but I'm having trouble manually running metro on my code base to make sure it's working since `react-native-community/cli` is using an older version of `metro` and updating it seems to be a bigger project

**Test plan**

### CODE REVIEW

**Comment by ChristopherGillis** [comment]
Would be good to get this security patch merged asap!

**Comment by everything-zen** [comment]
Any update on getting this merged ?

**Comment by MichielDeMey** [comment]
I'm not sure you can just bump the dependency like this? 🤔
Have we looked at the failing tests?

**Comment by cpojer** [comment]
Thanks for the update. Unfortunately these updates have to be done at FB and cannot be merged via GitHub. I'll look into upgrade the `ws` dependency.

**Comment by gwmccull** [comment]
thanks @cpojer!

**Pull request closed without merging**
