### PR TITLE
Upgrading to yargs@13.0.0 to remove dependency on mem package

### PR DESCRIPTION
**Pull request by timglass**
**Summary**
Remove dependency on os-locale which in turn has a dependency on mem package (commit [4dfa19b](https://github.com/yargs/yargs/commit/4dfa19b3275cbd74ed686c437d392c4612e237a4)), which has a vulnerability (WS-2018-0236).

This PR resolves issue #414.

**Test plan**
Run `npm test` both prior to and after checking out this branch, to ensure no existing tests are broken

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Can we get this merged please?

**Comment by cpojer** [comment]
Unfortunately we can't merge package updates via GitHub and have to do them at FB. We have a ton of stuff depending on Yargs so we may not be able to update this in Metro soon :( Sorry about that.

**Comment by henrikra** [comment]
@cpojer Looks like the current master nowadays has the updated version. In which React Native this will be released?

**Comment by covolution** [comment]
There's no fix version or milestone on this, its still in the latest version of expo ```expo@37 -> react-native@0.61.4 -> metro@0.56.4``` . How can we tell when there is a release that fixes this?

**Comment by cpojer** [comment]
It's in Metro 0.59.

**Pull request closed without merging**
