### PR TITLE
Translate website

### PR DESCRIPTION
**Pull request by anchengjian**
**Summary**

add translate for Metro.

**Test plan**
no test case.

create a [crowdin project](https://crowdin.com/project/metro/) by [docusaurus docs](https://docusaurus.io/docs/en/next/translation).

and, I'm very happy to transfer the project to you.

show time~
image
image
image

### CODE REVIEW

**Comment by anchengjian** [comment]
@wangliguang 你在 https://crowdin.com/project/metro/zh-CN# 这个里面进行编辑就可以了

**Comment by wangliguang** [comment]
@anchengjian  那个文档有点搞不明白，加微信聊？ wangliguangios

**Comment by anchengjian** [comment]
@cpojer We have finished the translation work, Could you review it for us? 😄

**Comment by relign** [comment]
666

**Comment by cpojer** [comment]
Hello! Thank you so much for working on this translation! Because of how Metro is set up with FB, I recommend hosting your own version of the translated Metro website. I hope that is ok and makes sense to you :)

**Pull request closed without merging**
