### PR TITLE
Uglify terser copy

### PR DESCRIPTION
**Pull request by haggholm**
**Summary**

Add support for using [terser](https://github.com/fabiosantoscode/terser/). `terser` is a fork of `uglify-es`, which is not really maintained; and maintains API compatibility with `uglify-es`.

In order to avoid duplicating configuration like default options in `metro-minify-uglify`, this PR adds a parameter to `metro-minify-uglify` that allows passing in an alternative minifier module, and the new package `metro-minify-terser` calls this, passing in `terser`.

This is based on discussion in https://github.com/facebook/metro/issues/230.

After earlier submitting https://github.com/facebook/metro/pull/243, I created this alternative PR to address comments from @rafeca 

**Test plan**

The tests are simply copied from `metro-minify-uglify`, since the API is and the results should be identical.

### CODE REVIEW

**Comment by DimitryDushkin** [comment]
Hey! How to use it?

**Comment by skurgansky-sugarcrm** [comment]
I would like to know too..

**Comment by DimitryDushkin** [comment]
> I would like to know too..

Hey! For RN 57 this `rn-cli.config.js` works:
```
module.exports = {
    transformer: {
        minifierPath: 'metro-minify-terser'
    }
};
```
also
`npm i -D metro-minify-terser`

**Comment by skurgansky-sugarcrm** [comment]
@DimitryDushkin  thanks for response ! btw in RN 0.59.1 there is new `metro.config.js`. should I use it to replace `rn-cli.config.js` ? It's a pity there was no comments in docs about that.

**Comment by radiosilence** [comment]
Hey, I'm trying to use this now and I get this error:

```

TypeError: Cannot read properties of undefined (reading 'match')
```

**Comment by grit96** [comment]
@radiosilence did you figure out a workaround for this?

**Comment by robhogan** [comment]
If you're seeing `Cannot read properties of undefined (reading 'match').`, be sure to use a version of `metro-minify-terser` that matches your `metro` version. See #767.

**Comment by grit96** [comment]
Thanks, I suppose installing a newer version of metro doesn't work as it's tied to the react-native version (my package.json has metro, metro-minify-terser and metro-react-native-babel-preset at 0.70.1).

**Pull request closed without merging**
