### PR TITLE
Update DependencyGraph.js

### PR DESCRIPTION
**Pull request by louisjacksonrees**
This is a PR to fix the issue outlined here: #330

### CODE REVIEW

**Comment by crramirez** [comment]
Works for me thanks a lot

**Comment by jamonholmgren** [comment]
Looks like the CI issue is just a linting error -- missing a semicolon.

**Comment by DuncanWalter** [comment]
👋 Just bumping this PR. I've been running into issue #330 trying to work with linked packages, and would love to have this change or something equivalent published

**Comment by BaderSerhan** [comment]
Hello. Thanks for the PR! I started to have this issue out of nowhere! Any idea on when will it be merged?

**Comment by mjesun** [comment]
Hi! Original implementor of the Metro caching strategies here 🙂

Metro uses different techniques to watch for file changes in the filesystem. It does that by relying in `jest-haste-map`, which implements two strategies for watching: `watchman`, if it's available on your machine, and `fs.watch` otherwise. In either case, `jest-haste-map` provides you the SHA-1s of the files being watched.

When `jest-haste-map` *isn't watching a file*, the SHA-1 will not be returned. Of course we could have computed it the SHA ourselves at first in the `if` where this PR is adding it - and this would make Metro build -, but if you tried changing the file nothing will happen, because the file is not monitored. To make Metro monitor the file, you need to add the folder where it's placed to the `projectRoots` configuration setting.

I however agree that the message is not great. It explains the internal error but not why this is important or any actionable feedback; it should mention why the SHA-1 is important (for caching purposes, why it couldn't be obtained (because you require a file not being watched by Metro), and how to fix it (make your file(s) watchable by adding the folder in which they are to `projectRoots`).

**Comment by cpojer** [comment]
Thank you for the thorough explanation @mjesun. I'll close this PR but I'm happy to merge a new PR that improves on this message.

**Pull request closed without merging**
