### PR TITLE
fix(website): add Algolia search API key

### PR DESCRIPTION
**Pull request by shortcuts**
**Summary**

This PR update the docusaurus config to expose the Algolia search API key.

_note: Algolia search API keys can be disclosed publicly_

**Motivation**

Search does not work on the production website.

**Test plan**

- `cd website`
- `yarn start`
- Search

### CODE REVIEW

**Comment by shortcuts** [comment]
Since then, we've migrated to our new infra: https://docsearch.algolia.com/docs/migrating-from-legacy

Update credentials in https://github.com/facebook/metro/pull/726/commits/2b9306a3c51866b0b16d1f0916b5ac241b583973 to reflect that.

cc @rh389

**Comment by rh389** [comment]
Thanks @shortcuts and sorry this has taken so long for us to get around to! 

I'm not personally familiar with our Algolia account - where do these values come from?

**Comment by shortcuts** [comment]
> Thanks @shortcuts and sorry this has taken so long for us to get around to!
> 
> I'm not personally familiar with our Algolia account - where do these values come from?

No problem! Team members of the account have receive an email with those keys, you can also find them here https://www.algolia.com/account/api-keys/all?applicationId=T38HJZTD87

**Comment by rh389** [comment]
> I only see @cpojer as team members of this app. Should I add you?

Ah, yes, please - me and @motiz88. I'll email you.

**Pull request closed without merging**
